project:
  type: book
  resources:
  - webr-serviceworker.js
  - webr-worker.js
  - coi-serviceworker.js
book:
  title: The Heinsberg Lab
  author: Lacey W. Heinsberg, PhD, RN 
  date: today
  date-format: long
  chapters:
  - index.qmd
  - intro.qmd
  - team.qmd
  - recent_pubs.qmd
  - woohoo.qmd
  - foafoaga.qmd  
  - hope.qmd
  - grow.qmd
  - eetr.qmd
  - training.qmd
format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/lwheinsberg\.github\.io\/HeinsbergLab'
editor: visual
